### ISSUE TITLE
TypeError: LocalTaskQueue.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by DrRaja** [PropsAI/agentserve#4]
Hi,
Thank you for the clean package! 
I was using it without any hassles, but the latest release 0.2.8 introduced the following bug:

```bash
2024-11-15 18:12:51,320 - agentserve.server - INFO - Initializing local task queue
2024-11-15 18:12:51,322 - agentserve.server - ERROR - Failed to initialize task queue: LocalTaskQueue.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\agentserve-project\main.py", line 30, in <module>
    app = agentserve.app()
          ^^^^^^^^^^^^^^^^
  File "D:\agentserve-project\agntsrv\Lib\site-packages\agentserve\agent_server.py", line 18, in __init__
    self.task_queue = self._initialize_task_queue()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\agentserve-project\agntsrv\Lib\site-packages\agentserve\agent_server.py", line 36, in _initialize_task_queue
    return LocalTaskQueue(self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LocalTaskQueue.__init__() takes 1 positional argument but 2 were given

```

**Comment by k11kirky** [comment]
I apologize this has been fixed as part of v0.2.9
